name: Daily Stock Delivery Alert

on:
  schedule:
    - cron: '30 0 * * *'   # 6:00 AM IST daily
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-delivery-alert:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run new delivery script with good mail
      run: |
        echo "🚀 Starting new delivery script..."
        python Delivery_good_mail.py
        echo "✅ New script execution completed"
