name: Daily Stock Delivery % Alert 

on:
  schedule:
    - cron: '30 0 * * *'   # 6:00 AM IST daily (00:30 UTC)
    #- cron: '30 10 * * *'   # 4:00 PM IST daily (10:30 UTC)
    #- cron: '0 9 * * *'   # 2:30 PM IST daily
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-delivery-alert:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run delivery script with formatted email
      run: |
        echo "🚀 Starting delivery script..."
        python Delivery_good_mail.py
        echo "✅ Script execution completed"
